# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Core Tests

on:
  push:
    branches: 
      - main
  pull_request:
    branches: [ main ]
  #allow to run CI manually in action
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Update Git Deploy Tokens
        run: |
          git config --global credential.helper 'store --file ~/.git-credentials'
          echo "https://git:${{ secrets.CI_DEPLOY_TOKEN }}@github.com" > ~/.git-credentials
      - name: Install dependencies
        run: |
          sudo apt-get update -y && sudo apt-get install -y git unzip tar
          python -m pip install --upgrade pip
          git clone https://github.com/shellphish-support-syndicate/agentlib.git && pip install ./agentlib
          git clone https://github.com/shellphish-support-syndicate/clang-indexer.git && pip install ./clang-indexer
          pip install .[test]
      - name: Configure Env
        run: |
          git config --global user.email "example@example.com"
          git config --global user.name "Example Name"
        
      - name: Pytest
        run: |
          export LITELLM_KEY=${{ secrets.LITELLM_KEY }}
          export AIXCC_LITELLM_HOSTNAME='http://beatty.unfiltered.seclab.cs.ucsb.edu:4000'
          export RETRIEVAL_API='http://beatty.unfiltered.seclab.cs.ucsb.edu:48751'
          export EMBEDDING_API='http://beatty.unfiltered.seclab.cs.ucsb.edu:49152'          
          pytest ./tests/test_core.py

      - name: Ping cause CI failure
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_CI_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            ðŸ¤¡ <@819684919427989565>, <@593280144962224138>, & <@405072293782487045> join ðŸŽª because `${{ github.event.repository.name }}`'s internal CI tests are broken.

            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

        if: failure() && github.ref == 'refs/heads/main'


